### ISSUE TITLE
can you build libtorrent for Universal Library or simulator iphone ?

### ISSUE THREAD

**Issue by bapzangbo** [chublix/libtorrent-ios-builded#1]
hi @chublix . im try using your lib, but cannot build on simulator device of mac osx. Can you build for architechture such as arm64, armv7, i386, and x86_64. at last, using lipo -c to compile all lib to universal lib
Im watting response from you. thanks for your attention

**Comment by chublix** [comment]
Hi! I am trying to build new verision libttorrent like universal lib in 
last week (I using lipo for assembly "fat" binary), but now I have some 
problem with linking this library to another projects (i think it 
problem with newest compiler). When I fix it problem I upload updated 
lib to github. Best regards.

7/1/15 06:50, bapzangbo пишет:
